version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: echo "hello world in build"

  test:
      docker:
        - image: circleci/openjdk:8-jdk

      steps:
        - checkout
        - run: echo "hello world in test"